/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */


import {
  LandingPage as IconSearch
} from './components/icon-search/icon-search';

interface HTMLIconSearchElement extends IconSearch, HTMLElement {
}
declare var HTMLIconSearchElement: {
  prototype: HTMLIconSearchElement;
  new (): HTMLIconSearchElement;
};
declare global {
  interface HTMLElementTagNameMap {
      "icon-search": HTMLIconSearchElement;
  }
  interface ElementTagNameMap {
      "icon-search": HTMLIconSearchElement;
  }
  namespace JSX {
      interface IntrinsicElements {
          "icon-search": JSXElements.IconSearchAttributes;
      }
  }
  namespace JSXElements {
      export interface IconSearchAttributes extends HTMLAttributes {
          mode?: string,
          color?: string,
        
      }
  }
}


import {
  LandingPage as LandingPage
} from './components/landing-page/landing-page';

interface HTMLLandingPageElement extends LandingPage, HTMLElement {
}
declare var HTMLLandingPageElement: {
  prototype: HTMLLandingPageElement;
  new (): HTMLLandingPageElement;
};
declare global {
  interface HTMLElementTagNameMap {
      "landing-page": HTMLLandingPageElement;
  }
  interface ElementTagNameMap {
      "landing-page": HTMLLandingPageElement;
  }
  namespace JSX {
      interface IntrinsicElements {
          "landing-page": JSXElements.LandingPageAttributes;
      }
  }
  namespace JSXElements {
      export interface LandingPageAttributes extends HTMLAttributes {
          mode?: string,
          color?: string,
        
      }
  }
}

